num_envs: 200
num_eval_envs: 1000
lr: 0.0003
max_it: 10000
max_grad_norm: 0.4
seed: 0
system_config: smpl
demo_replay_mode: threshold
threshold: 0.2
replay_rate: 0.05
early_termination: False
normalize_observations: True
ep_len: 60
ep_len_eval: 120
use_lr_scheduler: False
reward_scaling: 0.02
truncation_length: 30
rot_weight: 0.25
vel_weight: 0.08
ang_weight: 0.02
foot_weight: 0.0
motion_dir: data/humanml3d_processed
beta: 0.0
weight_decay: 0.0
deterministic: True
skip_encoder: True
large: True